// GENERATED FILE - DO NOT EDIT BY HAND.
// Source: Unicode Character Database 17.0.0
// (UnicodeData.txt, Scripts.txt, ScriptExtensions.txt, PropList.txt,
//  DerivedCoreProperties.txt, DerivedNormalizationProps.txt, emoji-data.txt,
//  PropertyAliases.txt, PropertyValueAliases.txt).
// Regenerated by scripts in the regexp-conformance work; see regexp/unicode/mod.rs.

mod binary_0;
mod binary_1;
mod binary_2;
mod gc_0;
mod gc_1;
mod script_0;
mod script_1;
mod scx_0;
mod scx_1;
mod scx_2;

pub fn gc_ranges(name: &str) -> Option<&'static [(u32, u32)]> {
    if let Some(r) = gc_0::lookup(name) {
        return Some(r);
    }
    if let Some(r) = gc_1::lookup(name) {
        return Some(r);
    }
    None
}

pub fn script_ranges(name: &str) -> Option<&'static [(u32, u32)]> {
    if let Some(r) = script_0::lookup(name) {
        return Some(r);
    }
    if let Some(r) = script_1::lookup(name) {
        return Some(r);
    }
    None
}

pub fn script_ext_ranges(name: &str) -> Option<&'static [(u32, u32)]> {
    if let Some(r) = scx_0::lookup(name) {
        return Some(r);
    }
    if let Some(r) = scx_1::lookup(name) {
        return Some(r);
    }
    if let Some(r) = scx_2::lookup(name) {
        return Some(r);
    }
    None
}

pub fn binary_ranges(name: &str) -> Option<&'static [(u32, u32)]> {
    if let Some(r) = binary_0::lookup(name) {
        return Some(r);
    }
    if let Some(r) = binary_1::lookup(name) {
        return Some(r);
    }
    if let Some(r) = binary_2::lookup(name) {
        return Some(r);
    }
    None
}
