// GENERATED FILE - DO NOT EDIT BY HAND.
// Source: Unicode Character Database 17.0.0
// (UnicodeData.txt, Scripts.txt, ScriptExtensions.txt, PropList.txt,
//  DerivedCoreProperties.txt, DerivedNormalizationProps.txt, emoji-data.txt,
//  PropertyAliases.txt, PropertyValueAliases.txt).
// Regenerated by scripts in the regexp-conformance work; see regexp/unicode/mod.rs.

#[rustfmt::skip]
pub static SC_OLD_NORTH_ARABIAN: &[(u32, u32)] = &[
    (0x10a80,0x10a9f),
];

#[rustfmt::skip]
pub static SC_OLD_PERMIC: &[(u32, u32)] = &[
    (0x10350,0x1037a),
];

#[rustfmt::skip]
pub static SC_OLD_PERSIAN: &[(u32, u32)] = &[
    (0x103a0,0x103c3),(0x103c8,0x103d5),
];

#[rustfmt::skip]
pub static SC_OLD_SOGDIAN: &[(u32, u32)] = &[
    (0x10f00,0x10f27),
];

#[rustfmt::skip]
pub static SC_OLD_SOUTH_ARABIAN: &[(u32, u32)] = &[
    (0x10a60,0x10a7f),
];

#[rustfmt::skip]
pub static SC_OLD_TURKIC: &[(u32, u32)] = &[
    (0x10c00,0x10c48),
];

#[rustfmt::skip]
pub static SC_OLD_UYGHUR: &[(u32, u32)] = &[
    (0x10f70,0x10f89),
];

#[rustfmt::skip]
pub static SC_ORIYA: &[(u32, u32)] = &[
    (0xb01,0xb03),(0xb05,0xb0c),(0xb0f,0xb10),(0xb13,0xb28),(0xb2a,0xb30),(0xb32,0xb33),(0xb35,0xb39),(0xb3c,0xb44),
    (0xb47,0xb48),(0xb4b,0xb4d),(0xb55,0xb57),(0xb5c,0xb5d),(0xb5f,0xb63),(0xb66,0xb77),
];

#[rustfmt::skip]
pub static SC_OSAGE: &[(u32, u32)] = &[
    (0x104b0,0x104d3),(0x104d8,0x104fb),
];

#[rustfmt::skip]
pub static SC_OSMANYA: &[(u32, u32)] = &[
    (0x10480,0x1049d),(0x104a0,0x104a9),
];

#[rustfmt::skip]
pub static SC_PAHAWH_HMONG: &[(u32, u32)] = &[
    (0x16b00,0x16b45),(0x16b50,0x16b59),(0x16b5b,0x16b61),(0x16b63,0x16b77),(0x16b7d,0x16b8f),
];

#[rustfmt::skip]
pub static SC_PALMYRENE: &[(u32, u32)] = &[
    (0x10860,0x1087f),
];

#[rustfmt::skip]
pub static SC_PAU_CIN_HAU: &[(u32, u32)] = &[
    (0x11ac0,0x11af8),
];

#[rustfmt::skip]
pub static SC_PHAGS_PA: &[(u32, u32)] = &[
    (0xa840,0xa877),
];

#[rustfmt::skip]
pub static SC_PHOENICIAN: &[(u32, u32)] = &[
    (0x10900,0x1091b),(0x1091f,0x1091f),
];

#[rustfmt::skip]
pub static SC_PSALTER_PAHLAVI: &[(u32, u32)] = &[
    (0x10b80,0x10b91),(0x10b99,0x10b9c),(0x10ba9,0x10baf),
];

#[rustfmt::skip]
pub static SC_REJANG: &[(u32, u32)] = &[
    (0xa930,0xa953),(0xa95f,0xa95f),
];

#[rustfmt::skip]
pub static SC_RUNIC: &[(u32, u32)] = &[
    (0x16a0,0x16ea),(0x16ee,0x16f8),
];

#[rustfmt::skip]
pub static SC_SAMARITAN: &[(u32, u32)] = &[
    (0x800,0x82d),(0x830,0x83e),
];

#[rustfmt::skip]
pub static SC_SAURASHTRA: &[(u32, u32)] = &[
    (0xa880,0xa8c5),(0xa8ce,0xa8d9),
];

#[rustfmt::skip]
pub static SC_SHARADA: &[(u32, u32)] = &[
    (0x11180,0x111df),(0x11b60,0x11b67),
];

#[rustfmt::skip]
pub static SC_SHAVIAN: &[(u32, u32)] = &[
    (0x10450,0x1047f),
];

#[rustfmt::skip]
pub static SC_SIDDHAM: &[(u32, u32)] = &[
    (0x11580,0x115b5),(0x115b8,0x115dd),
];

#[rustfmt::skip]
pub static SC_SIDETIC: &[(u32, u32)] = &[
    (0x10940,0x10959),
];

#[rustfmt::skip]
pub static SC_SIGNWRITING: &[(u32, u32)] = &[
    (0x1d800,0x1da8b),(0x1da9b,0x1da9f),(0x1daa1,0x1daaf),
];

#[rustfmt::skip]
pub static SC_SINHALA: &[(u32, u32)] = &[
    (0xd81,0xd83),(0xd85,0xd96),(0xd9a,0xdb1),(0xdb3,0xdbb),(0xdbd,0xdbd),(0xdc0,0xdc6),(0xdca,0xdca),(0xdcf,0xdd4),
    (0xdd6,0xdd6),(0xdd8,0xddf),(0xde6,0xdef),(0xdf2,0xdf4),(0x111e1,0x111f4),
];

#[rustfmt::skip]
pub static SC_SOGDIAN: &[(u32, u32)] = &[
    (0x10f30,0x10f59),
];

#[rustfmt::skip]
pub static SC_SORA_SOMPENG: &[(u32, u32)] = &[
    (0x110d0,0x110e8),(0x110f0,0x110f9),
];

#[rustfmt::skip]
pub static SC_SOYOMBO: &[(u32, u32)] = &[
    (0x11a50,0x11aa2),
];

#[rustfmt::skip]
pub static SC_SUNDANESE: &[(u32, u32)] = &[
    (0x1b80,0x1bbf),(0x1cc0,0x1cc7),
];

#[rustfmt::skip]
pub static SC_SUNUWAR: &[(u32, u32)] = &[
    (0x11bc0,0x11be1),(0x11bf0,0x11bf9),
];

#[rustfmt::skip]
pub static SC_SYLOTI_NAGRI: &[(u32, u32)] = &[
    (0xa800,0xa82c),
];

#[rustfmt::skip]
pub static SC_SYRIAC: &[(u32, u32)] = &[
    (0x700,0x70d),(0x70f,0x74a),(0x74d,0x74f),(0x860,0x86a),
];

#[rustfmt::skip]
pub static SC_TAGALOG: &[(u32, u32)] = &[
    (0x1700,0x1715),(0x171f,0x171f),
];

#[rustfmt::skip]
pub static SC_TAGBANWA: &[(u32, u32)] = &[
    (0x1760,0x176c),(0x176e,0x1770),(0x1772,0x1773),
];

#[rustfmt::skip]
pub static SC_TAI_LE: &[(u32, u32)] = &[
    (0x1950,0x196d),(0x1970,0x1974),
];

#[rustfmt::skip]
pub static SC_TAI_THAM: &[(u32, u32)] = &[
    (0x1a20,0x1a5e),(0x1a60,0x1a7c),(0x1a7f,0x1a89),(0x1a90,0x1a99),(0x1aa0,0x1aad),
];

#[rustfmt::skip]
pub static SC_TAI_VIET: &[(u32, u32)] = &[
    (0xaa80,0xaac2),(0xaadb,0xaadf),
];

#[rustfmt::skip]
pub static SC_TAI_YO: &[(u32, u32)] = &[
    (0x1e6c0,0x1e6de),(0x1e6e0,0x1e6f5),(0x1e6fe,0x1e6ff),
];

#[rustfmt::skip]
pub static SC_TAKRI: &[(u32, u32)] = &[
    (0x11680,0x116b9),(0x116c0,0x116c9),
];

#[rustfmt::skip]
pub static SC_TAMIL: &[(u32, u32)] = &[
    (0xb82,0xb83),(0xb85,0xb8a),(0xb8e,0xb90),(0xb92,0xb95),(0xb99,0xb9a),(0xb9c,0xb9c),(0xb9e,0xb9f),(0xba3,0xba4),
    (0xba8,0xbaa),(0xbae,0xbb9),(0xbbe,0xbc2),(0xbc6,0xbc8),(0xbca,0xbcd),(0xbd0,0xbd0),(0xbd7,0xbd7),(0xbe6,0xbfa),
    (0x11fc0,0x11ff1),(0x11fff,0x11fff),
];

#[rustfmt::skip]
pub static SC_TANGSA: &[(u32, u32)] = &[
    (0x16a70,0x16abe),(0x16ac0,0x16ac9),
];

#[rustfmt::skip]
pub static SC_TANGUT: &[(u32, u32)] = &[
    (0x16fe0,0x16fe0),(0x17000,0x18aff),(0x18d00,0x18d1e),(0x18d80,0x18df2),
];

#[rustfmt::skip]
pub static SC_TELUGU: &[(u32, u32)] = &[
    (0xc00,0xc0c),(0xc0e,0xc10),(0xc12,0xc28),(0xc2a,0xc39),(0xc3c,0xc44),(0xc46,0xc48),(0xc4a,0xc4d),(0xc55,0xc56),
    (0xc58,0xc5a),(0xc5c,0xc5d),(0xc60,0xc63),(0xc66,0xc6f),(0xc77,0xc7f),
];

#[rustfmt::skip]
pub static SC_THAANA: &[(u32, u32)] = &[
    (0x780,0x7b1),
];

#[rustfmt::skip]
pub static SC_THAI: &[(u32, u32)] = &[
    (0xe01,0xe3a),(0xe40,0xe5b),
];

#[rustfmt::skip]
pub static SC_TIBETAN: &[(u32, u32)] = &[
    (0xf00,0xf47),(0xf49,0xf6c),(0xf71,0xf97),(0xf99,0xfbc),(0xfbe,0xfcc),(0xfce,0xfd4),(0xfd9,0xfda),
];

#[rustfmt::skip]
pub static SC_TIFINAGH: &[(u32, u32)] = &[
    (0x2d30,0x2d67),(0x2d6f,0x2d70),(0x2d7f,0x2d7f),
];

#[rustfmt::skip]
pub static SC_TIRHUTA: &[(u32, u32)] = &[
    (0x11480,0x114c7),(0x114d0,0x114d9),
];

#[rustfmt::skip]
pub static SC_TODHRI: &[(u32, u32)] = &[
    (0x105c0,0x105f3),
];

#[rustfmt::skip]
pub static SC_TOLONG_SIKI: &[(u32, u32)] = &[
    (0x11db0,0x11ddb),(0x11de0,0x11de9),
];

#[rustfmt::skip]
pub static SC_TOTO: &[(u32, u32)] = &[
    (0x1e290,0x1e2ae),
];

#[rustfmt::skip]
pub static SC_TULU_TIGALARI: &[(u32, u32)] = &[
    (0x11380,0x11389),(0x1138b,0x1138b),(0x1138e,0x1138e),(0x11390,0x113b5),(0x113b7,0x113c0),(0x113c2,0x113c2),(0x113c5,0x113c5),(0x113c7,0x113ca),
    (0x113cc,0x113d5),(0x113d7,0x113d8),(0x113e1,0x113e2),
];

#[rustfmt::skip]
pub static SC_UGARITIC: &[(u32, u32)] = &[
    (0x10380,0x1039d),(0x1039f,0x1039f),
];

#[rustfmt::skip]
pub static SC_VAI: &[(u32, u32)] = &[
    (0xa500,0xa62b),
];

#[rustfmt::skip]
pub static SC_VITHKUQI: &[(u32, u32)] = &[
    (0x10570,0x1057a),(0x1057c,0x1058a),(0x1058c,0x10592),(0x10594,0x10595),(0x10597,0x105a1),(0x105a3,0x105b1),(0x105b3,0x105b9),(0x105bb,0x105bc),
];

#[rustfmt::skip]
pub static SC_WANCHO: &[(u32, u32)] = &[
    (0x1e2c0,0x1e2f9),(0x1e2ff,0x1e2ff),
];

#[rustfmt::skip]
pub static SC_WARANG_CITI: &[(u32, u32)] = &[
    (0x118a0,0x118f2),(0x118ff,0x118ff),
];

#[rustfmt::skip]
pub static SC_YEZIDI: &[(u32, u32)] = &[
    (0x10e80,0x10ea9),(0x10eab,0x10ead),(0x10eb0,0x10eb1),
];

#[rustfmt::skip]
pub static SC_YI: &[(u32, u32)] = &[
    (0xa000,0xa48c),(0xa490,0xa4c6),
];

#[rustfmt::skip]
pub static SC_ZANABAZAR_SQUARE: &[(u32, u32)] = &[
    (0x11a00,0x11a47),
];

pub fn lookup(name: &str) -> Option<&'static [(u32, u32)]> {
    match name {
        "Old_North_Arabian" => Some(SC_OLD_NORTH_ARABIAN),
        "Old_Permic" => Some(SC_OLD_PERMIC),
        "Old_Persian" => Some(SC_OLD_PERSIAN),
        "Old_Sogdian" => Some(SC_OLD_SOGDIAN),
        "Old_South_Arabian" => Some(SC_OLD_SOUTH_ARABIAN),
        "Old_Turkic" => Some(SC_OLD_TURKIC),
        "Old_Uyghur" => Some(SC_OLD_UYGHUR),
        "Oriya" => Some(SC_ORIYA),
        "Osage" => Some(SC_OSAGE),
        "Osmanya" => Some(SC_OSMANYA),
        "Pahawh_Hmong" => Some(SC_PAHAWH_HMONG),
        "Palmyrene" => Some(SC_PALMYRENE),
        "Pau_Cin_Hau" => Some(SC_PAU_CIN_HAU),
        "Phags_Pa" => Some(SC_PHAGS_PA),
        "Phoenician" => Some(SC_PHOENICIAN),
        "Psalter_Pahlavi" => Some(SC_PSALTER_PAHLAVI),
        "Rejang" => Some(SC_REJANG),
        "Runic" => Some(SC_RUNIC),
        "Samaritan" => Some(SC_SAMARITAN),
        "Saurashtra" => Some(SC_SAURASHTRA),
        "Sharada" => Some(SC_SHARADA),
        "Shavian" => Some(SC_SHAVIAN),
        "Siddham" => Some(SC_SIDDHAM),
        "Sidetic" => Some(SC_SIDETIC),
        "SignWriting" => Some(SC_SIGNWRITING),
        "Sinhala" => Some(SC_SINHALA),
        "Sogdian" => Some(SC_SOGDIAN),
        "Sora_Sompeng" => Some(SC_SORA_SOMPENG),
        "Soyombo" => Some(SC_SOYOMBO),
        "Sundanese" => Some(SC_SUNDANESE),
        "Sunuwar" => Some(SC_SUNUWAR),
        "Syloti_Nagri" => Some(SC_SYLOTI_NAGRI),
        "Syriac" => Some(SC_SYRIAC),
        "Tagalog" => Some(SC_TAGALOG),
        "Tagbanwa" => Some(SC_TAGBANWA),
        "Tai_Le" => Some(SC_TAI_LE),
        "Tai_Tham" => Some(SC_TAI_THAM),
        "Tai_Viet" => Some(SC_TAI_VIET),
        "Tai_Yo" => Some(SC_TAI_YO),
        "Takri" => Some(SC_TAKRI),
        "Tamil" => Some(SC_TAMIL),
        "Tangsa" => Some(SC_TANGSA),
        "Tangut" => Some(SC_TANGUT),
        "Telugu" => Some(SC_TELUGU),
        "Thaana" => Some(SC_THAANA),
        "Thai" => Some(SC_THAI),
        "Tibetan" => Some(SC_TIBETAN),
        "Tifinagh" => Some(SC_TIFINAGH),
        "Tirhuta" => Some(SC_TIRHUTA),
        "Todhri" => Some(SC_TODHRI),
        "Tolong_Siki" => Some(SC_TOLONG_SIKI),
        "Toto" => Some(SC_TOTO),
        "Tulu_Tigalari" => Some(SC_TULU_TIGALARI),
        "Ugaritic" => Some(SC_UGARITIC),
        "Vai" => Some(SC_VAI),
        "Vithkuqi" => Some(SC_VITHKUQI),
        "Wancho" => Some(SC_WANCHO),
        "Warang_Citi" => Some(SC_WARANG_CITI),
        "Yezidi" => Some(SC_YEZIDI),
        "Yi" => Some(SC_YI),
        "Zanabazar_Square" => Some(SC_ZANABAZAR_SQUARE),
        _ => None,
    }
}
