// GENERATED FILE - DO NOT EDIT BY HAND.
// Source: Unicode Character Database 17.0.0
// (UnicodeData.txt, Scripts.txt, ScriptExtensions.txt, PropList.txt,
//  DerivedCoreProperties.txt, DerivedNormalizationProps.txt, emoji-data.txt,
//  PropertyAliases.txt, PropertyValueAliases.txt).
// Regenerated by scripts in the regexp-conformance work; see regexp/unicode/mod.rs.

#[rustfmt::skip]
pub static SCX_TAKR: &[(u32, u32)] = &[
    (0x964,0x965),(0xa830,0xa839),
];

#[rustfmt::skip]
pub static SCX_TAKRI: &[(u32, u32)] = &[
    (0x11680,0x116b9),(0x116c0,0x116c9),
];

#[rustfmt::skip]
pub static SCX_TALE: &[(u32, u32)] = &[
    (0x300,0x301),(0x307,0x308),(0x30c,0x30c),(0x1040,0x1049),
];

#[rustfmt::skip]
pub static SCX_TAMIL: &[(u32, u32)] = &[
    (0xb82,0xb83),(0xb85,0xb8a),(0xb8e,0xb90),(0xb92,0xb95),(0xb99,0xb9a),(0xb9c,0xb9c),(0xb9e,0xb9f),(0xba3,0xba4),
    (0xba8,0xbaa),(0xbae,0xbb9),(0xbbe,0xbc2),(0xbc6,0xbc8),(0xbca,0xbcd),(0xbd0,0xbd0),(0xbd7,0xbd7),(0xbe6,0xbfa),
    (0x11fc0,0x11ff1),(0x11fff,0x11fff),
];

#[rustfmt::skip]
pub static SCX_TAML: &[(u32, u32)] = &[
    (0x951,0x952),(0x964,0x965),(0xbe6,0xbf3),(0x1cda,0x1cda),(0xa8f3,0xa8f3),(0x11301,0x11301),(0x11303,0x11303),(0x1133b,0x1133c),
    (0x11fd0,0x11fd1),(0x11fd3,0x11fd3),
];

#[rustfmt::skip]
pub static SCX_TANG: &[(u32, u32)] = &[
    (0x2ff0,0x2fff),(0x31ef,0x31ef),
];

#[rustfmt::skip]
pub static SCX_TANGSA: &[(u32, u32)] = &[
    (0x16a70,0x16abe),(0x16ac0,0x16ac9),
];

#[rustfmt::skip]
pub static SCX_TANGUT: &[(u32, u32)] = &[
    (0x16fe0,0x16fe0),(0x17000,0x18aff),(0x18d00,0x18d1e),(0x18d80,0x18df2),
];

#[rustfmt::skip]
pub static SCX_TELU: &[(u32, u32)] = &[
    (0x951,0x952),(0x964,0x965),(0x1cd5,0x1cd6),(0x1cd8,0x1cd8),(0x1cda,0x1cda),(0x1cf2,0x1cf2),
];

#[rustfmt::skip]
pub static SCX_TELUGU: &[(u32, u32)] = &[
    (0xc00,0xc0c),(0xc0e,0xc10),(0xc12,0xc28),(0xc2a,0xc39),(0xc3c,0xc44),(0xc46,0xc48),(0xc4a,0xc4d),(0xc55,0xc56),
    (0xc58,0xc5a),(0xc5c,0xc5d),(0xc60,0xc63),(0xc66,0xc6f),(0xc77,0xc7f),
];

#[rustfmt::skip]
pub static SCX_TFNG: &[(u32, u32)] = &[
    (0x302,0x302),(0x304,0x304),(0x306,0x309),(0x323,0x323),
];

#[rustfmt::skip]
pub static SCX_TGLG: &[(u32, u32)] = &[
    (0x1735,0x1736),
];

#[rustfmt::skip]
pub static SCX_THAA: &[(u32, u32)] = &[
    (0x60c,0x60c),(0x61b,0x61c),(0x61f,0x61f),(0x660,0x669),(0xfdf2,0xfdf2),(0xfdfd,0xfdfd),
];

#[rustfmt::skip]
pub static SCX_THAANA: &[(u32, u32)] = &[
    (0x780,0x7b1),
];

#[rustfmt::skip]
pub static SCX_THAI: &[(u32, u32)] = &[
    (0x2bc,0x2bc),(0x2d7,0x2d7),(0x303,0x303),(0x331,0x331),(0xe01,0xe3a),(0xe40,0xe5b),
];

#[rustfmt::skip]
pub static SCX_TIBETAN: &[(u32, u32)] = &[
    (0xf00,0xf47),(0xf49,0xf6c),(0xf71,0xf97),(0xf99,0xfbc),(0xfbe,0xfcc),(0xfce,0xfd4),(0xfd9,0xfda),
];

#[rustfmt::skip]
pub static SCX_TIBT: &[(u32, u32)] = &[
    (0x3008,0x300b),
];

#[rustfmt::skip]
pub static SCX_TIFINAGH: &[(u32, u32)] = &[
    (0x2d30,0x2d67),(0x2d6f,0x2d70),(0x2d7f,0x2d7f),
];

#[rustfmt::skip]
pub static SCX_TIRH: &[(u32, u32)] = &[
    (0x951,0x952),(0x964,0x965),(0x1cd5,0x1cd5),(0x1ce2,0x1ce2),(0x1cf2,0x1cf2),(0xa830,0xa839),
];

#[rustfmt::skip]
pub static SCX_TIRHUTA: &[(u32, u32)] = &[
    (0x11480,0x114c7),(0x114d0,0x114d9),
];

#[rustfmt::skip]
pub static SCX_TODHRI: &[(u32, u32)] = &[
    (0x105c0,0x105f3),
];

#[rustfmt::skip]
pub static SCX_TODR: &[(u32, u32)] = &[
    (0x301,0x301),(0x304,0x304),(0x307,0x307),(0x311,0x311),(0x313,0x313),(0x35e,0x35e),
];

#[rustfmt::skip]
pub static SCX_TOLONG_SIKI: &[(u32, u32)] = &[
    (0x11db0,0x11ddb),(0x11de0,0x11de9),
];

#[rustfmt::skip]
pub static SCX_TOTO: &[(u32, u32)] = &[
    (0x2bc,0x2bc),(0x1e290,0x1e2ae),
];

#[rustfmt::skip]
pub static SCX_TULU_TIGALARI: &[(u32, u32)] = &[
    (0x11380,0x11389),(0x1138b,0x1138b),(0x1138e,0x1138e),(0x11390,0x113b5),(0x113b7,0x113c0),(0x113c2,0x113c2),(0x113c5,0x113c5),(0x113c7,0x113ca),
    (0x113cc,0x113d5),(0x113d7,0x113d8),(0x113e1,0x113e2),
];

#[rustfmt::skip]
pub static SCX_TUTG: &[(u32, u32)] = &[
    (0xce6,0xcef),(0x1cf2,0x1cf2),(0x1cf4,0x1cf4),(0xa830,0xa835),(0xa8f1,0xa8f1),
];

#[rustfmt::skip]
pub static SCX_UGARITIC: &[(u32, u32)] = &[
    (0x10380,0x1039d),(0x1039f,0x1039f),
];

#[rustfmt::skip]
pub static SCX_VAI: &[(u32, u32)] = &[
    (0xa500,0xa62b),
];

#[rustfmt::skip]
pub static SCX_VITHKUQI: &[(u32, u32)] = &[
    (0x10570,0x1057a),(0x1057c,0x1058a),(0x1058c,0x10592),(0x10594,0x10595),(0x10597,0x105a1),(0x105a3,0x105b1),(0x105b3,0x105b9),(0x105bb,0x105bc),
];

#[rustfmt::skip]
pub static SCX_WANCHO: &[(u32, u32)] = &[
    (0x1e2c0,0x1e2f9),(0x1e2ff,0x1e2ff),
];

#[rustfmt::skip]
pub static SCX_WARANG_CITI: &[(u32, u32)] = &[
    (0x118a0,0x118f2),(0x118ff,0x118ff),
];

#[rustfmt::skip]
pub static SCX_YEZI: &[(u32, u32)] = &[
    (0x60c,0x60c),(0x61b,0x61b),(0x61f,0x61f),(0x660,0x669),
];

#[rustfmt::skip]
pub static SCX_YEZIDI: &[(u32, u32)] = &[
    (0x10e80,0x10ea9),(0x10eab,0x10ead),(0x10eb0,0x10eb1),
];

#[rustfmt::skip]
pub static SCX_YI: &[(u32, u32)] = &[
    (0xa000,0xa48c),(0xa490,0xa4c6),
];

#[rustfmt::skip]
pub static SCX_YIII: &[(u32, u32)] = &[
    (0x3001,0x3002),(0x3008,0x3011),(0x3014,0x301b),(0x30fb,0x30fb),(0xff61,0xff65),
];

#[rustfmt::skip]
pub static SCX_ZANABAZAR_SQUARE: &[(u32, u32)] = &[
    (0x11a00,0x11a47),
];

pub fn lookup(name: &str) -> Option<&'static [(u32, u32)]> {
    match name {
        "Takr" => Some(SCX_TAKR),
        "Takri" => Some(SCX_TAKRI),
        "Tale" => Some(SCX_TALE),
        "Tamil" => Some(SCX_TAMIL),
        "Taml" => Some(SCX_TAML),
        "Tang" => Some(SCX_TANG),
        "Tangsa" => Some(SCX_TANGSA),
        "Tangut" => Some(SCX_TANGUT),
        "Telu" => Some(SCX_TELU),
        "Telugu" => Some(SCX_TELUGU),
        "Tfng" => Some(SCX_TFNG),
        "Tglg" => Some(SCX_TGLG),
        "Thaa" => Some(SCX_THAA),
        "Thaana" => Some(SCX_THAANA),
        "Thai" => Some(SCX_THAI),
        "Tibetan" => Some(SCX_TIBETAN),
        "Tibt" => Some(SCX_TIBT),
        "Tifinagh" => Some(SCX_TIFINAGH),
        "Tirh" => Some(SCX_TIRH),
        "Tirhuta" => Some(SCX_TIRHUTA),
        "Todhri" => Some(SCX_TODHRI),
        "Todr" => Some(SCX_TODR),
        "Tolong_Siki" => Some(SCX_TOLONG_SIKI),
        "Toto" => Some(SCX_TOTO),
        "Tulu_Tigalari" => Some(SCX_TULU_TIGALARI),
        "Tutg" => Some(SCX_TUTG),
        "Ugaritic" => Some(SCX_UGARITIC),
        "Vai" => Some(SCX_VAI),
        "Vithkuqi" => Some(SCX_VITHKUQI),
        "Wancho" => Some(SCX_WANCHO),
        "Warang_Citi" => Some(SCX_WARANG_CITI),
        "Yezi" => Some(SCX_YEZI),
        "Yezidi" => Some(SCX_YEZIDI),
        "Yi" => Some(SCX_YI),
        "Yiii" => Some(SCX_YIII),
        "Zanabazar_Square" => Some(SCX_ZANABAZAR_SQUARE),
        _ => None,
    }
}
